/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DiseaseAnalysisService } from "../diseaseAnalysis.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DiseaseAnalysisCreateInput } from "./DiseaseAnalysisCreateInput";
import { DiseaseAnalysis } from "./DiseaseAnalysis";
import { DiseaseAnalysisFindManyArgs } from "./DiseaseAnalysisFindManyArgs";
import { DiseaseAnalysisWhereUniqueInput } from "./DiseaseAnalysisWhereUniqueInput";
import { DiseaseAnalysisUpdateInput } from "./DiseaseAnalysisUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DiseaseAnalysisControllerBase {
  constructor(
    protected readonly service: DiseaseAnalysisService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DiseaseAnalysis })
  @nestAccessControl.UseRoles({
    resource: "DiseaseAnalysis",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDiseaseAnalysis(
    @common.Body() data: DiseaseAnalysisCreateInput
  ): Promise<DiseaseAnalysis> {
    return await this.service.createDiseaseAnalysis({
      data: data,
      select: {
        createdAt: true,
        id: true,
        prediction: true,
        recommendations: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DiseaseAnalysis] })
  @ApiNestedQuery(DiseaseAnalysisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DiseaseAnalysis",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diseaseAnalyses(
    @common.Req() request: Request
  ): Promise<DiseaseAnalysis[]> {
    const args = plainToClass(DiseaseAnalysisFindManyArgs, request.query);
    return this.service.diseaseAnalyses({
      ...args,
      select: {
        createdAt: true,
        id: true,
        prediction: true,
        recommendations: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DiseaseAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseAnalysis",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diseaseAnalysis(
    @common.Param() params: DiseaseAnalysisWhereUniqueInput
  ): Promise<DiseaseAnalysis | null> {
    const result = await this.service.diseaseAnalysis({
      where: params,
      select: {
        createdAt: true,
        id: true,
        prediction: true,
        recommendations: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DiseaseAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseAnalysis",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDiseaseAnalysis(
    @common.Param() params: DiseaseAnalysisWhereUniqueInput,
    @common.Body() data: DiseaseAnalysisUpdateInput
  ): Promise<DiseaseAnalysis | null> {
    try {
      return await this.service.updateDiseaseAnalysis({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          prediction: true,
          recommendations: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DiseaseAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiseaseAnalysis",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDiseaseAnalysis(
    @common.Param() params: DiseaseAnalysisWhereUniqueInput
  ): Promise<DiseaseAnalysis | null> {
    try {
      return await this.service.deleteDiseaseAnalysis({
        where: params,
        select: {
          createdAt: true,
          id: true,
          prediction: true,
          recommendations: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
