/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClaimPredictionService } from "../claimPrediction.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClaimPredictionCreateInput } from "./ClaimPredictionCreateInput";
import { ClaimPrediction } from "./ClaimPrediction";
import { ClaimPredictionFindManyArgs } from "./ClaimPredictionFindManyArgs";
import { ClaimPredictionWhereUniqueInput } from "./ClaimPredictionWhereUniqueInput";
import { ClaimPredictionUpdateInput } from "./ClaimPredictionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClaimPredictionControllerBase {
  constructor(
    protected readonly service: ClaimPredictionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClaimPrediction })
  @nestAccessControl.UseRoles({
    resource: "ClaimPrediction",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClaimPrediction(
    @common.Body() data: ClaimPredictionCreateInput
  ): Promise<ClaimPrediction> {
    return await this.service.createClaimPrediction({
      data: data,
      select: {
        billingAgent: true,
        claimAmount: true,
        claimStatus: true,
        createdAt: true,
        id: true,
        medicalCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ClaimPrediction] })
  @ApiNestedQuery(ClaimPredictionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClaimPrediction",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async claimPredictions(
    @common.Req() request: Request
  ): Promise<ClaimPrediction[]> {
    const args = plainToClass(ClaimPredictionFindManyArgs, request.query);
    return this.service.claimPredictions({
      ...args,
      select: {
        billingAgent: true,
        claimAmount: true,
        claimStatus: true,
        createdAt: true,
        id: true,
        medicalCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClaimPrediction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimPrediction",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async claimPrediction(
    @common.Param() params: ClaimPredictionWhereUniqueInput
  ): Promise<ClaimPrediction | null> {
    const result = await this.service.claimPrediction({
      where: params,
      select: {
        billingAgent: true,
        claimAmount: true,
        claimStatus: true,
        createdAt: true,
        id: true,
        medicalCode: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClaimPrediction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimPrediction",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClaimPrediction(
    @common.Param() params: ClaimPredictionWhereUniqueInput,
    @common.Body() data: ClaimPredictionUpdateInput
  ): Promise<ClaimPrediction | null> {
    try {
      return await this.service.updateClaimPrediction({
        where: params,
        data: data,
        select: {
          billingAgent: true,
          claimAmount: true,
          claimStatus: true,
          createdAt: true,
          id: true,
          medicalCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClaimPrediction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimPrediction",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClaimPrediction(
    @common.Param() params: ClaimPredictionWhereUniqueInput
  ): Promise<ClaimPrediction | null> {
    try {
      return await this.service.deleteClaimPrediction({
        where: params,
        select: {
          billingAgent: true,
          claimAmount: true,
          claimStatus: true,
          createdAt: true,
          id: true,
          medicalCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
